### ISSUE TITLE
overhaul certificate signing

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/chain-libs#18]
general improvement to signing

* [x] cleanup signing capability
* [x] overhaul signing to be flexible to multi owners and different algorithms
* [x] transaction binding mechanism
* [ ] document the security guarantees
